### ISSUE TITLE
jquery能否换成其他版本

### ISSUE THREAD

**Issue by 404157386** [tianxiangbing/paging#1]
你好，我看了你的jquery-1.11.2的源码，为什么跟官方发布的版本不一样，加了一段amd代码。
能不能将jquery替换成其他版本?

**Comment by tianxiangbing** [comment]
可以替换成其他jquery版本,最好是1.7以上的版本。

**Comment by 404157386** [comment]
你好，我用官网发布的jquery-1.11.2替换了你的jq，但是会报错
paging.js:21 Uncaught TypeError: Cannot read property 'fn' of undefined
请问你有改过jquery源码吗

**Comment by tianxiangbing** [comment]
没有啊，就是从官网上下载的，你引用顺序对不对，还是你的jquery下载的不完整啊，fn是$的一个原型啊，乍会没有。

**Comment by 404157386** [comment]
我引用你的demo里面的jq是可以正常加载出来的，但是我想把jq替换成其他版本就报错了。
我看你的jq里面有amd判断的代码
if ( typeof define === "function" && define.amd ) {
	define( "jquery", [], function() {
		return jQuery;
	});
}
但是官网上面的这个版本jq是没有这个判断的
打断点到报错那一行会提示$未定义。

**Comment by 404157386** [comment]
我看了你的paging.js和query.js的代码require jQuery，都是用“$”这个模块id来代替默认的“jquery”。
我查了一下requirejs官网，上面说AMD插件引入jQuery的时候最好还是要用“jquery”这个模块id：

http://www.requirejs.cn/docs/jquery.html#modulename
_...since jQuery registers itself with the name of 'jquery' and not 'lib/jquery'. In general, explicitly naming modules in the define() call are discouraged, **but jQuery has some special constraints**._


https://github.com/requirejs/requirejs/wiki/Updating-existing-libraries#anon
_If jQuery is not loaded by an AMD script loader and there is an anonymous define call, that could lead to an error in loading, since the anonymous define call cannot be tied to a name that the loader was expecting. So, to ease into AMD loading on the web, **jQuery registers as a named module**..._

把你代码里面require的“$”改成“jquery”，不用配置shim，就可以用官网发布的其他版本jQuery了。

**Comment by tianxiangbing** [comment]
你如果是要用require.js的话才需要加上这一行的，如果不是的，就没关系。

**Comment by tianxiangbing** [comment]
对的，jQuery源码里面amd的兼容，可能是我搞错了。
