### ISSUE TITLE
paging和query的相关性

### ISSUE THREAD

**Issue by Huooo** [tianxiangbing/paging#2]
田大哥不考虑一下，paging和query能够分离开吗，可能在使用的时候不需要地址栏的页数显示，这个时候不引用query会报错，我只能在paging.js里面注释query相关，这个有其他方法吗？

**Comment by tianxiangbing** [comment]
在1.0.1的版本里是不需要引用query.js的。
我推荐的做法是，这两个文件合并引用，但你可以传递{hash:false}来禁用url的地址栏改变。

**Comment by Huooo** [comment]
是的，我看见你的合并使用了，但是这样一来，对于一个分页我引用的文件太大了。我先去看一下1.0.1版本的情况吧，谢谢。

**Comment by dfma05** [comment]
device2.html:322 Uncaught TypeError: $(...).Paging is not a function
    at paging (device2.html:322)
    at HTMLButtonElement.<anonymous> (device2.html:400)
    at HTMLButtonElement.dispatch (jquery-3.2.1.min.js:3)
    at HTMLButtonElement.q.handle (jquery-3.2.1.min.js:3)
paging @ device2.html:322
(anonymous) @ device2.html:400
dispatch @ jquery-3.2.1.min.js:3
q.handle @ jquery-3.2.1.min.js:3

**Comment by tianxiangbing** [comment]
在console里打印 一下，请检查一下文件引用的正确性和js执行顺序，不然使用new的方式调用paging
