### ISSUE TITLE
页码显示不正确

### ISSUE THREAD

**Issue by JohnCoffie** [tianxiangbing/paging#3]
![default](https://cloud.githubusercontent.com/assets/5676487/25983381/0bed0674-3717-11e7-9d00-f3f92fcc51b7.JPG)
分页多了之后页码显示不正确，本来应该进行数学计算的页码却变成了字符拼接了，请帮主帮忙修复，多谢！

**Comment by tianxiangbing** [comment]
@JohnCoffie ,你使用的版本？你可以看下示例，也是10几页，是没有你这个问题的。

**Comment by JohnCoffie** [comment]
从文件时间上来看，我用的就是你最新的版本1.0.4，这个问题是这样的，我发现当我从第一页点击第三页时，貌似导航栏一开始会正常显示4，但是很快的又变成了31了。同样的，如果从末页往前走也会出现类似问题，请看截图。
![2](https://cloud.githubusercontent.com/assets/5676487/25990155/4b36d9bc-3731-11e7-8d76-c2618518482c.JPG)
![3](https://cloud.githubusercontent.com/assets/5676487/25990158/4ead00b2-3731-11e7-8b45-e0ff8028b409.JPG)

**Comment by JohnCoffie** [comment]
我很喜欢你写的这个插件，特意在我的项目里用了你的这个工具。

**Comment by JohnCoffie** [comment]
`$(document).ready(function(){
	// Pagination initialization
	var p         = new Paging();
	var totalRows = $('#totalRows').val();
	var currPage  = $('#currPage').val();
	var pageSize  = $('#pageSize').val();

	p.init({
		target:   '#pageTool',
		pagesize: pageSize,
		current:  currPage,
		count:    totalRows,
		toolbar:  true,
		callback: function(page, size, count) {
			window.location.href = $ctx+"/scheduleMgmt/jobExecution/list?pageSize="+p.pagesize+"&currPage="+p.current;
		}
	});
});`

**Comment by JohnCoffie** [comment]
`上面是我使用的方式，html页面上再放一个<div id="pageTool">。`

**Comment by tianxiangbing** [comment]
@JohnCoffie 

var totalRows = $('#totalRows').val();
var currPage = $('#currPage').val();
var pageSize = $('#pageSize').val();
你这一块的值可能不是int类型的，需要转一下。
`
var totalRows = parseInt($('#totalRows').val());
var currPage = parseInt($('#currPage').val());
var pageSize = parseInt($('#pageSize').val());
`
还有你可能需要确保currPage的值是正确的。currPage一定要是Number类型的，不建议使用跳转的方式，如有需要，会在后面的版本中提供url跳转的，谢谢您的使用！

**Comment by JohnCoffie** [comment]
这两天被电脑病毒的事忙死了，才顾上看你的留言，谢谢作者！
