### ISSUE TITLE
点击下一页，报Uncaught TypeError: Cannot read property 'tagName' of null

### ISSUE THREAD

**Issue by balmainctf** [tianxiangbing/paging#4]
浏览器： chrome版本 59.0.3071.109 （64位）
mac serria os

欧朋浏览器不会报错

**Comment by tianxiangbing** [comment]
@balmainctf 你是打开这个例子链接http://tianxiangbing.github.io/paging/ 就会报错吗？还是你自己的项目才会报错？

**Comment by balmainctf** [comment]
@tianxiangbing   把项目拉下来打开就会报错，然后我查了这个链接里面也有同样的错误http://www.lovewebgames.com/jsmodule/paging.html#page=2

**Comment by tianxiangbing** [comment]
这要么就是jquery版本问题，要么就是浏览器版本问题，整个插件中没有涉及到tagName的操作
