### ISSUE TITLE
单击数字，触发分页，分页数字显示不对

### ISSUE THREAD

**Issue by nicky1** [tianxiangbing/paging#5]
1.看了代码，format函数的数字处理 直接使用  +，js可能当成字符串处理了，导致 8+1 = '81',应该parseint处理。

**Comment by jackfromcumt** [comment]
我也遇到了这个问题，请问大神有找到办法吗

**Comment by tianxiangbing** [comment]
@jackfromcumt 这个问题已经在最新的版本里修复过了。
