### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by kinoaa** [tianxiangbing/paging#8]
如果有两页数据，删除第二页最后一条，理论上从第二页跳到第一页，但是页码还在第二页
还有就是批量删除也存在这个问题

**Comment by tianxiangbing** [comment]
这个功能不是由分页来决定的，应该是你删除的动作确定的，你可以通过删除后来判断当前页是否还有记录，无记录时page.go(current-1)的方式来跳转。 @kinoaa

**Comment by kinoaa** [comment]
删除后我处理了下，解决了
/**
 * 
 * 分页问题处理函数
 * @param {object} obj 分页数据里面需包含每页条数pageSize和当前页码pageNum
 * @param {number} total 总条数
 * @param {number} abnormal 非正常分页，传入批量删除个数即可
 */
function base_page(obj, total, abnormal) {
	if (abnormal) {
		// 批量删除完后分页问题
		// 拿到总数totalNumber和页码obj.pageNum以及每页条数obj.pageSize
		let moreNub = total % obj.pageSize;//取余
		let pageSize = obj.pageSize;
		if (moreNub > 0) {
			pageSize = moreNub;
		}
		if (abnormal == pageSize) {
			let page = Math.ceil(total / obj.pageSize);
			if (page == obj.pageNum && obj.pageNum > 1) {
				obj.pageNum = obj.pageNum - 1;
			}
		}
	} else {
		// 正常单个删除完后分页问题
		let remainder = total % obj.pageSize;
		let pageNum = Math.ceil(total / obj.pageSize);//当前页码最后一页
		if (remainder == 1) {
			if (pageNum == obj.pageNum && obj.pageNum > 1) {
				obj.pageNum = obj.pageNum - 1;
			}
		}
	}
}
